{{- if (.Values.nginx).enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-jellyfin
  labels:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress
spec:
  rules:
  - host: {{ .Values.nginx.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin
            port: 
              number: 80
  ingressClassName: nginx
{{ end }}