{{- if (.Values.nginx).enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-transmission
  labels:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /transmission(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: transmission
            port: 
              number: 80
  ingressClassName: nginx
{{ end }}