apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  labels:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: jellyfin
spec:
  ports:
  - port: 80
    targetPort: 8096
  selector:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: jellyfin
