apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv-volume
  labels:
    type: config
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100M
  hostPath:
    path: /mnt/config
    type: DirectoryOrCreate