apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv-volume
  labels:
    type: config
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.storage.config.capacity }}
  hostPath:
    path: {{ .Values.storage.config.path }}
    type: DirectoryOrCreate