apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-volume
  labels:
    type: data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.storage.data.capacity }}
  hostPath:
    path: {{ .Values.storage.data.path }}
    type: DirectoryOrCreate