apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "helm-mediaserver.labels" . | nindent 6 }}
      app.kubernetes.io/component: transmission
  template:
    metadata:
      labels:
        {{- include "helm-mediaserver.labels" . | nindent 8 }}
        app.kubernetes.io/component: transmission
    spec:
      containers:
        - name: transmission
          image: {{ printf "%s:%s" (ternary "haugene/transmission-openvpn" "linuxserver/transmission" .Values.transmission.vpn) (default "latest" .Values.transmission.tag) }}
          imagePullPolicy: {{ include "helm-mediaserver.imagePullPolicy" .Values.transmission }}
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            {{- if .Values.transmission.vpn -}}
            - name: config
              subPath: transmission
              mountPath: /data/transmission-home
            - name: data
              subPath: torrents/completed
              mountPath: /data/completed
            - name: data
              subPath: torrents/incomplete
              mountPath: /data/incomplete
            {{ else }}
            - name: config
              subPath: transmission
              mountPath: /config
            - name: data
              subPath: torrents/completed
              mountPath: /downloads/complete
            - name: data
              subPath: torrents/incomplete
              mountPath: /downloads/incomplete
            - name: data
              subPath: torrents/watch
              mountPath: /watch
            {{ end }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-pv-claim
        - name: data
          persistentVolumeClaim:
            claimName: data-pv-claim