apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: transmission
spec:
  ports:
  - port: 9091
    targetPort: 9091
  selector:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: transmission
