apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: sonarr
spec:
  ports:
  - port: 80
    targetPort: 8989
  selector:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: sonarr
