apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "helm-mediaserver.labels" . | nindent 6 }}
      app.kubernetes.io/component: sonarr
  template:
    metadata:
      labels:
        {{- include "helm-mediaserver.labels" . | nindent 8 }}
        app.kubernetes.io/component: sonarr
    spec:
      containers:
        - name: sonarr
          image: {{ include "helm-mediaserver.image" .Values.sonarr }}
          imagePullPolicy: {{ include "helm-mediaserver.imagePullPolicy" .Values.sonarr }}
          ports:
            - name: http
              containerPort: 8989
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            {{- include "helm-mediaserver.basicEnvs" . | nindent 12 }}
          volumeMounts:
            - name: config
              subPath: sonarr
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-pv-claim
        - name: data
          persistentVolumeClaim:
            claimName: data-pv-claim