apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "helm-mediaserver.labels" . | nindent 6 }}
      app.kubernetes.io/component: radarr
  template:
    metadata:
      labels:
        {{- include "helm-mediaserver.labels" . | nindent 8 }}
        app.kubernetes.io/component: radarr
    spec:
      containers:
        - name: radarr
          image: {{ include "helm-mediaserver.image" .Values.radarr }}
          imagePullPolicy: {{ include "helm-mediaserver.imagePullPolicy" .Values.radarr }}
          ports:
            - name: http
              containerPort: 7878
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            {{- include "helm-mediaserver.basicEnvs" . | nindent 12 }}
          volumeMounts:
            - name: config
              subPath: radarr
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-pv-claim
        - name: data
          persistentVolumeClaim:
            claimName: data-pv-claim