apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: radarr
spec:
  ports:
  - port: 80
    targetPort: 7878
  selector:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: radarr
