{{- if and (.Values.transmission.vpn.enabled) (empty .Values.transmission.vpn.secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: transmission-vpncredentials
  labels:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ required "openvpn username is required to use VPN" (.Values.transmission.vpn.credentials.username | b64enc) }}
  password: {{ required "openvpn password is required to use VPN" (.Values.transmission.vpn.credentials.password | b64enc) }}
{{ end }}