apiVersion: v1
kind: Service
metadata:
  name: jackett
  labels:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: jackett
spec:
  ports:
  - port: 9117
    targetPort: 9117
  selector:
    {{- include "helm-mediaserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: jackett
